# Generated by Django 5.0.14 on 2025-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='color',
            field=models.CharField(default='#4DB6AC', max_length=7),
        ),
        migrations.AddField(
            model_name='collection',
            name='icon',
            field=models.CharField(default='heart', max_length=50),
        ),
        migrations.AlterField(
            model_name='collectionrecipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
