# Generated by Django 5.0.14 on 2025-07-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_collection_color_collection_icon_and_more'),
        ('recipes', '0003_remove_recipe_meal_type_recipe_total_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionrecipe',
            name='collection',
            field=models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='favorites.collection'),
        ),
        migrations.AlterField(
            model_name='collectionrecipe',
            name='recipe',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
