# Generated by Django 4.2.23 on 2025-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_collection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
