# Generated by Django 5.0.14 on 2025-07-19 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_meal_type_recipe_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
