# Generated by Django 4.2.23 on 2025-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_total_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_by_user', '-created_at'], name='recipe_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cuisine', '-created_at'], name='recipe_cuisine_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty', '-avg_rating'], name='recipe_difficulty_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-avg_rating', 'rating_count'], name='recipe_rating_popularity_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['prep_time', 'cook_time'], name='recipe_time_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at', 'avg_rating'], name='recipe_recent_rated_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='recipe_name_search_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_by_user', 'cuisine'], name='recipe_user_cuisine_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty', 'cuisine'], name='recipe_difficulty_cuisine_idx'),
        ),
    ]
