# Generated by Django 5.0.14 on 2025-07-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_alter_mealplanitem_id_alter_mealplan_unique_together'),
        ('recipes', '0003_remove_recipe_meal_type_recipe_total_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='analysis_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='plan_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='meal_plan',
            field=models.ForeignKey(db_column='meal_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_plans.mealplan'),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='recipe',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
