# Generated by Django 4.2.23 on 2025-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_mealplan_analysis_text_mealplan_plan_description_and_more'),
    ]

    operations = [
        # Remove the old unique constraint that prevents multiple recipes per meal type/day
        migrations.RunSQL(
            "ALTER TABLE meal_plan_items DROP CONSTRAINT IF EXISTS meal_plan_items_unique;",
            reverse_sql="ALTER TABLE meal_plan_items ADD CONSTRAINT meal_plan_items_unique UNIQUE (meal_plan_id, day_of_week, meal_type);"
        ),
        # Add new unique constraint that allows multiple recipes but prevents exact duplicates
        migrations.RunSQL(
            "ALTER TABLE meal_plan_items ADD CONSTRAINT meal_plan_items_unique_with_recipe UNIQUE (meal_plan_id, day_of_week, meal_type, recipe_id);",
            reverse_sql="ALTER TABLE meal_plan_items DROP CONSTRAINT IF EXISTS meal_plan_items_unique_with_recipe;"
        ),
    ]
