# Generated by Django 4.2.23 on 2025-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add_performance_indexes'),
        ('meal_plans', '0004_fix_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanitem',
            unique_together={('meal_plan', 'day_of_week', 'meal_type', 'recipe')},
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
