# Generated by Django 4.2.23 on 2025-07-29 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0005_alter_mealplanitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanitem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Number of servings (e.g., 1.0, 1.5, 2.0)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
